import Foundation

/// The typeset mathematical core of every algorithm lesson.
///
/// Keeping these formulae separate from the plain-language explanations makes
/// two promises explicit: prose remains readable, and mathematical notation is
/// valid LaTeX rather than an assortment of Unicode approximations.
enum TechniqueLatexCatalog {
    static func formula(for techniqueID: String) -> String? {
        formulas[techniqueID]
    }

    static var techniqueIDs: Set<String> { Set(formulas.keys) }

    private static let formulas: [String: String] = [
        "state-invariant": #"S_{i+1}=\mathrm{update}(S_i,a_i),\qquad \mathcal{I}(S_i)\ \mathrm{is\ true\ after\ step}\ i"#,
        "hash-set": #"x\in S:\ \mathcal{O}(1)\ \mathrm{average},\qquad x\in [s_1,\ldots,s_n]:\ \mathcal{O}(|S|)"#,
        "hash-map": #"f:\mathcal{K}\to\mathcal{V},\qquad k\mapsto f(k)"#,
        "opposing-pointers": #"[L,R]\supseteq\{\mathrm{all\ remaining\ candidates}\}"#,
        "read-write-pointers": #"a[0:w]=\mathrm{completed\ output\ for\ the\ processed\ prefix}"#,
        "fixed-window": #"W_{i+1}=W_i-a_i+a_{i+k}\quad\Longrightarrow\quad \mathcal{O}(1)\ \mathrm{per\ shift}"#,
        "variable-window": #"0\le L\le R\le n,\qquad \#\mathrm{moves}(L)+\#\mathrm{moves}(R)\le 2n"#,
        "lifo-stack": #"\mathrm{pop}\!\left(\mathrm{push}(S,x)\right)=x"#,
        "monotonic-stack": #"\#\mathrm{pushes}\le n,\quad \#\mathrm{pops}\le n\quad\Longrightarrow\quad \mathcal{O}(n)"#,
        "sentinel-rewiring": #"\mathrm{next}:V\to V\cup\{\varnothing\}"#,
        "fast-slow": #"(2t-t)\bmod c=t\bmod c=0\quad\mathrm{at\ a\ meeting}"#,
        "boundary-search": #"b\in[\mathrm{lo},\mathrm{hi}),\qquad \mathrm{hi}'-\mathrm{lo}'\le\left\lceil\frac{\mathrm{hi}-\mathrm{lo}}{2}\right\rceil"#,
        "answer-search": #"P(x)\Rightarrow P(y)\ \mathrm{for}\ y\ge x,\qquad x^*=\min\{x:P(x)\}"#,
        "sort-merge": #"[a,b]\cap[c,d]\ne\varnothing\iff c\le b\quad\mathrm{when}\ a\le c"#,
        "sweep-events": #"\mathrm{active}(t)=\sum_{x\le t}\Delta(x),\qquad \Delta\in\{-1,+1\}"#,
        "tree-dfs": #"F(v)=G\!\left(v,F(v_{\mathrm{left}}),F(v_{\mathrm{right}})\right),\qquad F(\varnothing)=F_0"#,
        "tree-bfs": #"Q_d=\{v:\mathrm{depth}(v)=d\},\qquad Q_{d+1}=\bigcup_{v\in Q_d}\mathrm{children}(v)"#,
        "fifo-queue": #"\mathrm{dequeue}\!\left(\mathrm{enqueue}(Q,x)\right)\ \mathrm{preserves\ insertion\ order}"#,
        "heap": #"a_{\mathrm{parent}(i)}\le a_i,\qquad \mathrm{height}=\lfloor\log_2 n\rfloor"#,
        "trie": #"v_p\xrightarrow{\ c\ }v_{pc}"#,
        "prefix-fallback": #"\pi_i=\max\{k<i+1:\ p[0:k]=p[i-k+1:i+1]\}"#,
        "graph-search": #"T(V,E)=\mathcal{O}(|V|+|E|)"#,
        "topological-sort": #"\mathrm{indegree}(v)=\left|\{u\in U:(u,v)\in E\}\right|"#,
        "disjoint-set": #"x\sim y\iff \mathrm{find}(x)=\mathrm{find}(y)"#,
        "choose-explore-undo": #"\mathrm{state}\xrightarrow{\mathrm{choose}}\mathrm{child}\xrightarrow{\mathrm{undo}}\mathrm{state}"#,
        "bit-mask": #"i\in S\iff \bigl(m\mathbin{\&}(1\ll i)\bigr)\ne0"#,
        "fast-power": #"x^{2k}=(x^2)^k,\qquad x^{2k+1}=x(x^2)^k"#,
        "memo-tabulation": #"F(s)=G\!\left(\{F(t):t\prec s\}\right),\qquad T=|\mathcal{S}|\cdot T_{\mathrm{transition}}"#,
        "greedy-choice": #"\exists O'\in\mathrm{OPT}:\ G\subseteq O'"#,
        "lis-tails": #"\mathrm{tails}[k]=\min\{x:\exists\ \mathrm{increasing\ subsequence\ of\ length}\ k+1\ \mathrm{ending\ at}\ x\}"#,
        "synthesis": #"n\approx10^5:\quad \mathcal{O}(n^2)\gg\mathcal{O}(n\log n)\ge\mathcal{O}(n)"#,
        "fenwick-tree": #"\mathrm{lowbit}(i)=i\mathbin{\&}(-i),\qquad i\leftarrow i\pm\mathrm{lowbit}(i)"#,
        "lru-map-list": #"\mathrm{map}:k\mapsto v_k,\qquad v_{\mathrm{LRU}}\leftrightarrow\cdots\leftrightarrow v_{\mathrm{MRU}}"#,
        "shape-indexing": #"C_{ij}=\sum_k A_{ik}B_{kj}"#,
        "stable-normalization": #"\mathrm{softmax}(x)_i=\frac{e^{x_i-m}}{\sum_j e^{x_j-m}},\qquad m=\max_jx_j"#,
        "computation-graph": #"\frac{\partial L}{\partial x}=\frac{\partial L}{\partial f}\frac{\partial f}{\partial g}\frac{\partial g}{\partial x}"#,
        "optimizer-state": #"m_t=\beta_1m_{t-1}+(1-\beta_1)g_t,\qquad v_t=\beta_2v_{t-1}+(1-\beta_2)g_t^2"#,
        "receptive-field": #"Y_{ij}=\sum_u\sum_vX_{i+u,j+v}K_{uv}"#,
        "attention": #"\mathrm{Attention}(Q,K,V)=\mathrm{softmax}\!\left(\frac{QK^{\mathsf T}}{\sqrt{d_k}}+M\right)V"#,
        "metric-accounting": #"\bar{x}=\frac{\sum_i n_i\bar{x}_i}{\sum_i n_i}"#,
        "ranked-state": #"k(x)=(-\mathrm{score}(x),\mathrm{token\ sequence}(x))"#,

        "linear-accumulator": #"S_i=\mathrm{fold}(a_0,\ldots,a_{i-1}),\qquad S_{i+1}=\mathrm{update}(S_i,a_i)"#,
        "canonical-key": #"x\sim y\iff f(x)=f(y)"#,
        "prefix-sums": #"P_0=0,\quad P_{i+1}=P_i+a_i,\quad \sum_{j=l}^{r-1}a_j=P_r-P_l"#,
        "prefix-suffix": #"\mathrm{answer}_i=L_iR_i"#,
        "known-total": #"\mathrm{missing}=\frac{n(n+1)}{2}-\sum_{x\in A}x"#,
        "boyer-moore": #"\#\{i:a_i=c\}>\frac{n}{2}"#,
        "deterministic-ranking": #"k(x)=(-\mathrm{frequency}(x),x)"#,
        "sequence-start-expansion": #"x\ \mathrm{starts\ a\ run}\iff x\in S\ \land\ x-1\notin S"#,
        "boundary-extremes": #"A(l,r)=(r-l)\min(h_l,h_r)"#,
        "sorted-k-sum": #"a_i+a_l+a_r=T\iff a_l+a_r=T-a_i"#,
        "merge-streams": #"\mathrm{next}=\min(a_i,b_j)"#,
        "subsequence-scan": #"\mathrm{matched}_i=\max\{k:t[0:k]\preceq s[0:i]\}"#,
        "two-sided-water": #"w_i=\max\!\left(0,\min(L_i,R_i)-h_i\right)"#,
        "pair-batch-counting": #"a_l+a_r<T\Rightarrow \#\{j:l<j\le r,\ a_l+a_j<T\}=r-l"#,
        "requirement-counts": #"\mathrm{satisfied}(c)\iff \mathrm{window}[c]\ge\mathrm{required}[c]"#,
        "monotonic-deque": #"i_1<i_2<\cdots<i_k,\qquad a_{i_1}>a_{i_2}>\cdots>a_{i_k}"#,
        "stale-window-maximum": #"\mathrm{replacements}=|W|-\max_c\mathrm{count}_W(c)"#,
        "balance-counter": #"b_i=\#\mathrm{opens}_{0:i}-\#\mathrm{matched\ closes}_{0:i}\ge0"#,
        "nested-frames": #"S=[F_0,F_1,\ldots,F_d],\qquad F_d=\mathrm{active\ frame}"#,
        "monotonic-span-boundaries": #"A=h(i-s)"#,
        "circular-scan": #"a_t=a_{t\bmod n},\qquad 0\le t<2n"#,
        "sentinel-index-boundary": #"\mathrm{length}=i-b,\qquad b_0=-1"#,
        "linked-traversal": #"v_0=\mathrm{head},\qquad v_{i+1}=\mathrm{next}(v_i),\qquad v_k=\varnothing"#,
        "floyd-cycle-entry": #"\mu\equiv-\lambda\pmod c"#,
        "rotated-search": #"a_{\mathrm{lo}}\le a_{\mathrm{mid}}\ \Longrightarrow\ [\mathrm{lo},\mathrm{mid}]\ \mathrm{is\ sorted}"#,
        "slope-search": #"a_i<a_{i+1}\ \Longrightarrow\ \exists j>i:\ a_{j-1}<a_j\ge a_{j+1}"#,
        "sorted-query-sweep": #"T(n,q)=\mathcal{O}(n\log n+q\log q+n+q)"#,
        "interval-streams": #"[a,b]\cap[c,d]=[\max(a,c),\min(b,d)]"#,
        "interval-scheduling": #"g=\operatorname*{arg\,min}_{I\ \mathrm{compatible}}\mathrm{end}(I)"#,
        "active-interval-heap": #"H_t=\{I:\mathrm{start}(I)\le t\le\mathrm{end}(I)\}"#,
        "heap-array-tree": #"\mathrm{parent}(i)=\left\lfloor\frac{i-1}{2}\right\rfloor,\quad \mathrm{left}(i)=2i+1,\quad \mathrm{right}(i)=2i+2"#,
        "heap-level-scan": #"L_d=[2^d-1,\,2^{d+1}-2],\qquad e_{d+1}=2e_d+2"#,
        "traversal-orders": #"\mathrm{pre}:NLR,\qquad \mathrm{in}:LNR,\qquad \mathrm{post}:LRN"#,
        "bst-invariants": #"\mathrm{low}<v<\mathrm{high}"#,
        "postorder-aggregation": #"R_v=v+\max(0,R_l,R_r),\qquad P_v=v+\max(0,R_l)+\max(0,R_r)"#,
        "dual-heaps": #"\max(L)\le\min(U),\qquad \bigl||L|-|U|\bigr|\le1"#,
        "counted-trie": #"\mathrm{count}(v_p)=|\{w:p\preceq w\}|"#,
        "graph-coloring": #"c:V\to\{0,1\},\qquad (u,v)\in E\Rightarrow c(u)\ne c(v)"#,
        "dijkstra": #"d_v\leftarrow\min(d_v,d_u+w_{uv})"#,
        "dfs-cycle-states": #"(u,v)\in E\ \land\ c(v)=\mathrm{active}\iff (u,v)\ \mathrm{is\ a\ back\ edge}"#,
        "kruskal": #"e^*=\operatorname*{arg\,min}_{e\in\delta(C)}w(e)\quad\mathrm{is\ safe}"#,
        "combination-search": #"S(i,p)=\{p\mathbin{+}q:q\subseteq a[i:n]\}"#,
        "permutation-search": #"n(n-1)\cdots1=n!"#,
        "constraint-pruning": #"\neg C(s)\Rightarrow \forall t\succeq s,\ t\notin\mathrm{Solutions}"#,
        "partition-search": #"E=\{(i,j):\mathrm{text}[i:j]\ \mathrm{is\ valid}\},\qquad 0\le i<j\le n"#,
        "popcount": #"x\leftarrow x\mathbin{\&}(x-1)"#,
        "xor-cancellation": #"x\oplus x=0,\qquad x\oplus0=x"#,
        "unbounded-amount-dp": #"dp[a]=1+\min_{c\le a}dp[a-c],\qquad dp[0]=0"#,
        "rolling-recurrence": #"dp_i=f(dp_{i-1},dp_{i-2})"#,
        "take-skip-dp": #"dp(s)=\max\!\left(dp(\mathrm{skip}(s)),\ v(s)+dp(\mathrm{take}(s))\right)"#,
        "grid-dp": #"dp_{r,c}=G(dp_{r-1,c},dp_{r,c-1})"#,
        "sequence-dp": #"dp_{i,j}=\begin{cases}1+dp_{i-1,j-1}&a_{i-1}=b_{j-1}\\\max(dp_{i-1,j},dp_{i,j-1})&a_{i-1}\ne b_{j-1}\end{cases}"#,
        "interval-dp": #"dp_{l,r}=G(dp_{l+1,r},dp_{l,r-1},dp_{l+1,r-1})"#,
        "cooldown-frame-counting": #"L=(f-1)(c+1)+m,\qquad \mathrm{answer}=\max(n,L)"#,
        "greedy-frontier": #"f_i=\max(f_{i-1},i+a_i)"#,
        "running-extreme": #"\mathrm{best}_i=x_i-\min_{j<i}x_j"#,
        "two-pass-constraints": #"a_i=\max(L_i,R_i)"#,
        "greedy-priority": #"t_{\mathrm{eligible}}=t_{\mathrm{used}}+c+1"#,
        "deficit-reset": #"\sum_{k=s}^{i}a_k<0\Rightarrow \forall j\in[s,i],\ j\ \mathrm{cannot\ be\ a\ valid\ start}"#,
        "last-occurrence-partitions": #"e_i=\max_{j\in[s,i]}\mathrm{last}(a_j),\qquad i=e_i\Rightarrow\mathrm{close}"#,
        "partition-binary-search": #"i+j=h,\qquad A_{i-1}\le B_j,\qquad B_{j-1}\le A_i"#,
        "quickselect": #"\mathbb{E}[T(n)]=T(n/2)+\mathcal{O}(n)=\mathcal{O}(n)"#,
        "multiway-merge": #"T(N,k)=\mathcal{O}(N\log k),\qquad |H|\le k"#,
        "kadane": #"e_i=\max(a_i,e_{i-1}+a_i),\qquad b_i=\max(b_{i-1},e_i)"#,
        "paired-product-extremes": #"M_i=\max(x_i,x_iM_{i-1},x_im_{i-1}),\qquad m_i=\min(x_i,x_iM_{i-1},x_im_{i-1})"#,
        "difference-array": #"d_l\mathrel{+}=\Delta,\quad d_{r+1}\mathrel{-}=\Delta,\quad a_i=\sum_{j=0}^{i}d_j"#,
        "log-likelihood": #"\log\mathrm{softmax}(z)_y=z_y-\left(m+\log\sum_j e^{z_j-m}\right)"#,
        "masked-reduction": #"\bar{x}=\frac{\sum_i m_ix_i}{\max(\sum_i m_i,1)}"#,
        "normalization": #"y=\gamma\frac{x-\mu}{\sqrt{\sigma^2+\varepsilon}}+\beta"#,
        "stochastic-training": #"y=\frac{mx}{1-p},\qquad m\sim\mathrm{Bernoulli}(1-p),\qquad \mathbb{E}[y]=x"#,
        "pooling": #"o=\left\lfloor\frac{i-k}{s}\right\rfloor+1"#,
        "attention-masking": #"P=\mathrm{softmax}(S+M),\qquad M_{qk}=\begin{cases}0&k\le q\\-\infty&k>q\end{cases}"#,
        "multihead-reshape": #"(B,T,Hd)\to(B,T,H,d)\to(B,H,T,d)"#,
        "clustering": #"c_i=\operatorname*{arg\,min}_k\|x_i-\mu_k\|_2^2,\qquad \mu_k=\frac{1}{|C_k|}\sum_{i\in C_k}x_i"#,
        "padding-masks": #"M_{bt}=\mathbf{1}[t<\ell_b]"#,
        "gradient-accumulation": #"g=\frac{\sum_i n_ig_i}{\sum_i n_i}"#
    ]
}

extension AlgorithmTechnique {
    var latexFormula: String? {
        TechniqueLatexCatalog.formula(for: id)
    }
}
